name: Standard
description: Lint the codebase with standardrb

runs:
  using: "composite"
  steps:
    - name: "[Lint] Standard"
      run: bin/standardrb --format github --parallel
      shell: bash
