name: Setup Ruby
description: Configure Ruby and bundle install

inputs:
  checkout:
    description: "Whether to check out the repository"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Checkout
      if: ${{ inputs.checkout == 'true' }}
      uses: actions/checkout@v3

    - name: 💎 Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
