name: Setup Node
description: Configure Node and yarn install

inputs:
  checkout:
    description: "Whether to check out the repository"
    required: false
    default: "false"
  registry-url:
    description: "URL of the registry to use"
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout
      if: ${{ inputs.checkout == 'true' }}
      uses: actions/checkout@v3

    - name: ⬢ Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: "16"
        registry-url: ${{ inputs.registry-url }}

    - name: ⬢ Fetch dependencies from cache
      id: cache-yarn
      uses: actions/cache@v3
      with:
        path: "**/node_modules"
        key: yarn-build-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          yarn-build-

    - name: ⬢ Install dependencies
      if: steps.cache-yarn.outputs.cache-hit != 'true'
      run: SKIP_SUBMODULE_DEPS=1 yarn --frozen-lockfile
      shell: bash
